name: Push CSV to Dashboard Repo
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Pushes CSV Only
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          source_file: 'etf_data.csv'
          destination_repo: '1155125384/webull_trade_24h'
          destination_folder: '' 
          user_email: '1155125384@link.cuhk.edu.hk'
          user_name: '1155125384'
          destination_branch: 'main'
          commit_msg: 'Auto-update ETF data'
