name: Push CSV to Dashboard Repo
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Isolate CSV into a temporary directory
        run: |
          mkdir temp_csv_folder
          cp etf_data.csv temp_csv_folder/

      - name: Push isolated folder to destination
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          source-directory: 'temp_csv_folder'
          destination-github-username: '1155125384'
          destination-repository-name: 'webull_trade_24h'
          target-directory: '' 
          user-email: '1155125384@link.cuhk.edu.hk'
          target-branch: 'main'
          commit-message: 'Auto-update ETF data'
